name : github-action-demo1

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  #pull_request:
  #  branches: [ "main" ]
# env:
#   file_name: demo.py  
#   name_id: hafsashakeel20
#   value: ${{ secrets.SECRET_VALUE }}

jobs:
  ubuntu-print:
    runs-on: ubuntu-latest
    # needs: env-var-job

    steps:
      - uses: actions/checkout@v3

      - name: Needs check
        run: echo Hi! im running within github with ubuntu

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project!!